apiVersion: v1
kind: Service
metadata:
  name: "translate-api"
  labels:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  selector:
    ai-services.io/service: {{ .Release.Name }}
    ai-services.io/component: translate-api
  ports:
    - name: translate-api
      port: 9000
      targetPort: 9000
      protocol: TCP
